name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./ yasser-shakoor-bootcamp-2020.surge.sh --token ${{secrets.SURGE_TOKEN}}
